services:
  takehome:
    build:
      context: .
    depends_on:
        cassandra-load-keyspace:
          condition: service_completed_successfully
          # condition: service_started # useful for subsequent runs - container exits with error if DB already exists
    ports: 
      - 3000:3000
    environment:
      - CASSANDRA_HOST=cassandra0
    entrypoint: /takehome

  cassandra0:
    image: cassandra:latest
    container_name: cassandra
    ports: 
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    restart: always
    volumes:
        - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:latest
      depends_on:
        cassandra0:
          condition: service_healthy
      volumes:
        - ./migrations/migration.cql:/schema.cql
      command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"